version: '3.4'

services:
  website:
    restart: unless-stopped
    build: ./website
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      GAME_SERVER_AUTHENTICATION_KEY: 'my-secret-auth-key'
    volumes:
      - ./website:/app
    entrypoint: gunicorn
    command: --bind 0.0.0.0:5000 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 wsgi:app --reload
    env_file:
      - './website/.env'

  worker:
    build: ./website
    command: watchmedo auto-restart --directory=./app --pattern=*.py --recursive -- celery --app run_celery.celery worker --pool=solo --loglevel=debug
    volumes:
      - ./website:/app
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - website
      - redis

  game-server-1:
    restart: unless-stopped
    build: ./game-server
    ports:
      - "5001:5001"
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      SERVER_IP: 127.0.0.1
      SERVER_PORT: 5001
      GAME_SERVER_AUTHENTICATION_KEY: 'my-secret-auth-key'
    volumes:
      - ./game-server:/app
    entrypoint: gunicorn
    command: --bind 0.0.0.0:5001 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 wsgi:app --reload
    env_file:
      - './game-server/.env'

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmx8oja23iojWEO23iooij
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  mongo:
    image: 'mongo'
    ports:
      - '27018:27017'
    volumes:
      - ./mongo-data:/data/db

volumes:
  cache:
    driver: local

  mongo-data:
